name: Spice Labs, Inc. Scan & Upload

description: Runs The Spice Labs CLI scan, then uploads results.

inputs:
  file_path:
    description: Path to local files to scan
    required: false
    default: .
  spice_pass:
    description: Spice Pass
    required: true

runs:
  using: "composite"
  steps:
    - name: Build ADG
      shell: bash
      run: |
        echo "🔍 Running The Spice Labs CLI Scan..."

        docker run \
          -v "${{ inputs.file_path }}:/input:ro" \
          -e SPICE_PASS="${{ inputs.spice_pass }}" \
          spicelabs/spice-labs-cli:latest \
          --verbose \
          --input /input

        echo "✅ ADG creation complete"
