name: "Spice Labs Surveyor"
description: "Runs The Spice Labs Surveyor to survey files and upload results."

inputs:
  file_path:
    description: "Path to local files to survey (deprecated, use 'input' instead)"
    required: false
    default: "."
  input:
    description: "Path to local files to survey"
    required: false
    default: "."
  spice_pass:
    description: "Spice Pass token"
    required: true
  tag:
    description: "Tag to associate with the survey"
    required: true
  cli_image:
    description: "Docker image for the CLI"
    required: false
    default: "spicelabs/spice-labs-cli"
  cli_image_tag:
    description: "Docker image tag for the CLI"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Install Spice Labs Surveyor CLI
      run: |
        curl -sSLf https://install.spicelabs.io | bash
    - name: Run Spice Labs Surveyor
      run: |
        export SPICE_PASS="${{ inputs.spice_pass }}"
        export SPICE_IMAGE="${{ inputs.cli_image }}"
        export SPICE_IMAGE_TAG="${{ inputs.cli_image_tag }}"

        # Prefer 'input'; if empty, fall back to deprecated 'file_path'
        INPUT_PATH="${{ inputs.input }}"
        if [ -z "$INPUT_PATH" ]; then
          INPUT_PATH="${{ inputs.file_path }}"
        fi
        
        ~/.local/bin/spice --input="$INPUT_PATH" --tag="${{ inputs.tag }}" --log-level=all
