name: Spice Grinder Scan & Upload

description: Runs Spice Grinder scan, then uploads results

inputs:
  file_path:
    description: Path to local files to scan
    required: false
    default: .
  spice_pass:
    description: Spice Pass
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Spice Grinder
      shell: bash
      run: |
        set -euxo pipefail
        echo "ðŸ” Running Grinder Scan..."
        docker run \
          -v "${{ inputs.file_path }}:/input:ro" \
          -e SPICE_PASS="${{ inputs.spice_pass }}" \
          spicelabs/grinder:latest \
          --input /input
        echo "âœ… Scan complete"

    - name: Check for Generated Files
      shell: bash
      run: |
        echo "ðŸ“ Checking if expected files exist..."
        SBOM="/tmp/sbom.spdx.json"
        ARTIFACTS=$(find "${{ inputs.file_path }}" -maxdepth 1 -name '*.oci.tar' 2>/dev/null || true)

        if [[ -f "$SBOM" ]]; then
          echo "âœ” Found SBOM: $SBOM"
        else
          echo "âš  No SBOM found at $SBOM"
        fi

        if [[ -n "$ARTIFACTS" ]]; then
          echo "âœ” Found OCI tar(s):"
          echo "$ARTIFACTS"
        else
          echo "âš  No .oci.tar files found in ${{ inputs.file_path }}"
        fi

    - name: Upload SBOM (if present)
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: /tmp/sbom.spdx.json
        if-no-files-found: warn

    - name: Upload OCI Tar(s) (if present)
      uses: actions/upload-artifact@v4
      with:
        name: oci-images
        path: ${{ inputs.file_path }}/*.oci.tar
        if-no-files-found: warn
